version: '3'

services:
  db:
    image: postgres:latest
    container_name: discord-db
    user: root
    restart: always
    volumes:
      - ${PWD}/.postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  backend:
    image: discord-backend
    container_name: discord-backend
    build: ./backend
    user: node
    depends_on:
      - db
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
      - ${PRISMA_STUDIO_PORT}:${PRISMA_STUDIO_PORT}
    volumes:
      - ./backend:/usr/src/app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - EXPRESS_PORT=${EXPRESS_PORT}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    env_file:
      - ./backend/.env

  # frontend:
  #   image: node:latest
  #   container_name: discord-frontend
  #   user: node
  #   depends_on:
  #     - express
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/frontend
  #   working_dir: /frontend
  #   command: 'npm run dev'
