-- AlterTable
ALTER TABLE "Block" ADD COLUMN     "sinceDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Friendship" ADD COLUMN     "sinceDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
