export enum RelationshipActions {
  SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST',
  REMOVE_FRIEND = 'REMOVE_FRIEND',
  ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST',
  BLOCK = 'BLOCK',
  UNBLOCK = 'UNBLOCK',
}
